[workspace]
resolver = "3"
members = [
    "evm",
    "evm-tests",
    "evm-block-execution"
]

[workspace.package]
authors = ["Aurora Labs <hello@aurora.dev>"]
edition = "2024"
version = "3.0.0"
description = "Aurora Ethereum Virtual Machine implementation written in pure Rust"
categories = ["no-std", "compilers", "cryptography::cryptocurrencies"]
keywords = ["aurora-evm", "evm", "ethereum", "blockchain", "no_std"]
repository = "https://github.com/aurora-is-near/aurora-evm"
license = "MIT"
readme = "README.md"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
as_conversions = "deny"
module_name_repetitions = "allow"

[workspace.dependencies]
aurora-engine-precompiles = "2.1"
aurora-evm = { path = "evm" }
auto_impl = "1.0"
hex = "0.4"
hex-literal = "1.1"
libsecp256k1 = "0.7"
primitive-types = { version = "0.13", default-features = false }
rlp = { version = "0.6", default-features = false }
sha2 = "0.10.0"
sha3 = { version = "0.10.0", default-features = false }
serde = { version = "1.0", default-features = false }

[patch.crates-io]
# Constrain to v0.14.6 to ensure compatibility with sha3 0.10 and prevent unexpected upgrades
generic-array = { git = "https://github.com/fizyk20/generic-array", rev = "effb209dd7e61b8226e194dec2979314e27598d1" }
